default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: localhost  # when using localhost
  host: db  # when using docker
  username: postgres
  password: postgres

development:
  <<: *default
  database: my_beers_development

test:
  <<: *default
  database: my_beers_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: my_beers_production
  username: my_beers
  password: <%= ENV['MY_BEERS_DATABASE_PASSWORD'] %>
  pool: 10
